/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hedymed_uart_SerialPortJNI */

#ifndef _Included_com_hedymed_uart_SerialPortJNI
#define _Included_com_hedymed_uart_SerialPortJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    setSpeed
 * Signature: (Ljava/io/FileDescriptor;I)I
 */
JNIEXPORT jint JNICALL Java_com_hedymed_uart_SerialPortJNI_setSpeed
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    setParity
 * Signature: (Ljava/io/FileDescriptor;III)I
 */
JNIEXPORT jint JNICALL Java_com_hedymed_uart_SerialPortJNI_setParity
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    openDev
 * Signature: (I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_hedymed_uart_SerialPortJNI_openDev
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    open485Dev
 * Signature: (I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_hedymed_uart_SerialPortJNI_open485Dev
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    closeDev
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_hedymed_uart_SerialPortJNI_closeDev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    close485Dev
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_hedymed_uart_SerialPortJNI_close485Dev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    readBytes
 * Signature: (Ljava/io/FileDescriptor;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_hedymed_uart_SerialPortJNI_readBytes
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    writeBytes
 * Signature: (Ljava/io/FileDescriptor;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hedymed_uart_SerialPortJNI_writeBytes
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     com_hedymed_uart_SerialPortJNI
 * Method:    set485mod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hedymed_uart_SerialPortJNI_set485mod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
